package com.wipro.servdemo;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Servlet implementation class Servlet1
 */
@WebServlet("/Servlet1")  // URL mapping for the servlet
public class Servlet1 extends HttpServlet {
    private static final long serialVersionUID = 1L;

    /**
     * Default constructor.
     */
    public Servlet1() {
        super();
    }

    /**
     * Initialization method, called once when the servlet is initialized.
     */
    @Override
    public void init() throws ServletException {
        // Initialization logic here
        System.out.println("Servlet Initialized.");
    }

    /**
     * Handles HTTP GET requests.
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Log when the GET request is processed
        System.out.println("GET request received.");

        // Set the response content type to HTML
        response.setContentType("text/html");

        // Get the writer to send a response
        PrintWriter out = response.getWriter();
        
        // Generate the HTML response
        out.println("<html><body>");
        out.println("<h1>Welcome to Servlet1 (GET)!</h1>");
        out.println("<p>This response was generated by the GET method of Servlet1.</p>");
        out.println("<p>Request received from: " + request.getRemoteAddr() + "</p>");
        out.println("<p>Context Path: " + request.getContextPath() + "</p>");
        out.println("<p>Servlet Path: " + request.getServletPath() + "</p>");
        out.println("</body></html>");
    }

    /**
     * Handles HTTP POST requests.
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Log when the POST request is processed
        System.out.println("POST request received.");

        // Call doGet to handle the POST request the same way
        doGet(request, response);
    }

    /**
     * Logs every service method call (can be useful for debugging).
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Log the service method when a request is processed
        System.out.println("Service method called for: " + request.getMethod());
        super.service(request, response);  // Call parent service method
    }

    /**
     * Provides basic information about the servlet.
     */
    @Override
    public String getServletInfo() {
        // Return the servlet info
        return "Servlet1 - A simple servlet example with GET and POST methods.";
    }

    /**
     * Cleanup resources when the servlet is destroyed.
     */
    @Override
    public void destroy() {
        // Log when the servlet is destroyed
        System.out.println("Servlet Destroyed.");
    }
}
